// <auto-generated />
namespace DiseasesProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addNameToDiet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNameToDiet));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111351050_addNameToDiet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
